import {store,dataMode,reload} from './store.js';
import {isSupabaseConfigured,getSession,signIn,signOut} from './supabase.js';
import {renderDashboard} from './dashboard.js';import {renderSale} from './sale.js';import {renderInventory} from './inventory.js';import {renderReceive} from './receive.js';import {renderPartners} from './partners.js';import {renderReports} from './reports.js';import {renderFraud} from './fraud.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
window.toast=m=>{const t=$('#toast');if(!t)return; t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
let role='';
function demoLogin(){document.querySelector('#app').innerHTML=`<section class="login"><div class="login-card"><img src="assets/logo.png"><h1>BIGBEAR ONE</h1><p>Production Pilot • Demo fallback</p><div class="notice">Supabase ยังไม่ได้ใส่ Project URL / anon key — ระบบจึงเปิดโหมดทดลอง</div><div class="role-grid">${['กรรมการบริษัท','ผู้จัดการสาขา','PC ประจำสาขา','เจ้าหน้าที่คลัง','Partner ร้าน','ฝ่ายบัญชี'].map(r=>`<button data-role="${r}">${r}</button>`).join('')}</div><button id="loginBtn" class="primary full" disabled>เข้าสู่ระบบทดลอง</button></div></section>`;$$('[data-role]').forEach(b=>b.onclick=()=>{$$('[data-role]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');role=b.dataset.role;$('#loginBtn').disabled=false});$('#loginBtn').onclick=shellView}
function authLogin(){document.querySelector('#app').innerHTML=`<section class="login"><div class="login-card"><img src="assets/logo.png"><h1>BIGBEAR ONE</h1><p>Production Pilot • Supabase Auth</p><div class="form"><label>Email<input id="email" type="email" autocomplete="username"></label><label>Password<input id="password" type="password" autocomplete="current-password"></label><button id="loginBtn" class="primary full">เข้าสู่ระบบ</button><div id="loginError" class="notice"></div></div></div></section>`;$('#loginBtn').onclick=async()=>{try{$('#loginBtn').disabled=true;await signIn($('#email').value.trim(),$('#password').value);await reload();shellView()}catch(e){$('#loginError').textContent=e.message;$('#loginBtn').disabled=false}}}
async function boot(){if(!isSupabaseConfigured())return demoLogin();try{const s=await getSession();if(s){await reload();shellView()}else authLogin()}catch(e){document.querySelector('#app').innerHTML=`<section class="login"><div class="login-card"><h1>เชื่อม Supabase ไม่สำเร็จ</h1><div class="notice">${e.message}</div></div></section>`}}
function shellView(){const mode=dataMode();document.querySelector('#app').innerHTML=`<div class="app"><aside class="sidebar" id="sidebar"><div class="brand"><img src="assets/logo.png"><div><strong>BIGBEAR ONE</strong><span>Production Pilot</span></div></div><div class="notice" style="margin:10px">DATA: ${mode==='supabase'?'SUPABASE':'DEMO'}</div><nav>${[['dashboard','⌂ ภาพรวม'],['today','✓ งานวันนี้'],['sale','▣ ขายสินค้า'],['inventory','▦ Inventory'],['receive','⇩ รับสินค้า'],['partners','♙ Partner'],['reports','▥ รายงาน'],['fraud','⚠ Fraud Test']].map((x,i)=>`<button class="${i===0?'active':''}" data-page="${x[0]}">${x[1]}</button>`).join('')}</nav><div class="userbox">${mode==='supabase'?'Authenticated User':'อัศวิน ชานัย'}<br><small>${role||mode}</small><br><button id="logout" class="soft">ออกจากระบบ</button></div></aside><main class="main"><header class="topbar"><button class="iconbtn menuBtn" id="menuBtn">☰</button><div class="searchbox"><input id="globalSearch" placeholder="ค้นหา ลูกค้า / IMEI / Serial / Barcode / เอกสาร / Partner"></div><button class="iconbtn" id="notifBtn">🔔</button><button class="primary" data-page="sale">+ ขายสินค้า</button></header><div class="content">${['dashboard','today','sale','inventory','receive','partners','reports','fraud'].map((x,i)=>`<section id="${x}" class="page ${i===0?'active':''}"></section>`).join('')}</div></main><nav class="bottomnav">${[['dashboard','⌂','หน้าแรก'],['today','✓','งานวันนี้'],['sale','▣','ขาย'],['inventory','▦','Stock'],['reports','▥','รายงาน']].map((x,i)=>`<button class="${i===0?'active':''} ${i===2?'scan':''}" data-page="${x[0]}">${x[1]}<span>${x[2]}</span></button>`).join('')}</nav></div><div class="modal" id="modal"><div class="panel"><div class="panelhead"><div><h2 id="modalTitle"></h2><p id="modalSub"></p></div><button class="close" id="modalClose">✕</button></div><div id="modalBody"></div></div></div><div id="toast"></div>`;
window.openModal=(title,sub,html)=>{$('#modalTitle').textContent=title;$('#modalSub').textContent=sub||'';$('#modalBody').innerHTML=html;$('#modal').classList.add('open')};$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#logout').onclick=async()=>{if(isSupabaseConfigured())await signOut();location.reload()};$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#notifBtn').onclick=openTasks;$('#globalSearch').oninput=e=>{if(e.target.value.length>=3)toast('กำลังค้นหา: '+e.target.value)};renderAll();setTimeout(openTasks,400)}
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
function openTasks(){const tasks=store().tasks||[];openModal('รายการค้างทั้งหมด','Action Center',tasks.length?tasks.map(t=>`<div class="drillcard"><b>${t.title||t.task_type||'-'}</b><small>${t.detail||t.status||''}</small></div>`).join(''):'<div class="notice">ยังไม่มีรายการค้าง</div>')}
function renderToday(){const tasks=store().tasks||[];$('#today').innerHTML=`<div class="pagehead"><div><small>Work Queue</small><h1>งานวันนี้</h1><p>${dataMode()==='supabase'?'ข้อมูลจาก Supabase':'ข้อมูล Demo'}</p></div></div><div class="taskgrid">${[['delivery','ลูกค้านัดรับเครื่อง'],['pending','เคสรอผลอนุมัติ'],['receive','รับของ Supplier'],['transfer','รอเซ็นรับโอน']].map(x=>{const c=tasks.filter(t=>(t.type||t.task_type)===x[0]).length;return `<button class="task" data-task="${x[0]}"><span>${x[1]}</span><b>${c}</b><small>คลิกดูรายละเอียด</small></button>`}).join('')}</div>`;$$('[data-task]').forEach(b=>b.onclick=()=>{const rows=tasks.filter(t=>(t.type||t.task_type)===b.dataset.task);openModal(b.querySelector('span').textContent,'รายละเอียด',rows.map(r=>`<div class="drillcard"><b>${r.title||'-'}</b><small>${r.detail||r.status||''}</small></div>`).join('')||'<div class="notice">ไม่มีรายการ</div>')})}
function renderAll(){renderDashboard();renderToday();renderSale();renderInventory();renderReceive();renderPartners();renderReports();renderFraud()}
window.refreshAll=renderAll;boot();
